version: '3'

services:
    ignite_server_node:
        image: apacheignite/ignite:2.8.1
        ports:
            - 47500:47500
            - 47100:47100
            - 11211:11211
            - 49112:49112
        environment:
            - IGNITE_WORK_DIR=/opt/ignite/work
        volumes:
            - ./.ignite:/opt/ignite/work
    micronaut:
        build: ./
        ports:
            - 8080:8080
