micronaut:
  application:
    name: micronaut-ignite-sample
  server:
    port: 8080
ignite:
  enabled: true
  discovery-spi:
    static-ip-finder:
      enabled: true
      addresses:
        - "127.0.0.1:47500"
        - "127.0.0.1:47501"
  cache-configurations:
    pet-store:
      enabled: true
  client-mode: true
